name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: '18'

    - name: Configure Maven
      uses: s4u/setup-maven@v2
      with:
        maven-version: '3.8.2'

    - name: Check Maven Version
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install -e -X

    - name: Run Placeholder Tests
      run: mvn test || echo "Nenhum teste implementado ainda"
